"""Add role_bot

Revision ID: 3789238ab743
Revises: a8de2840102f
Create Date: 2025-05-04 13:07:52.865518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3789238ab743'
down_revision: Union[str, None] = 'a8de2840102f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_history', sa.Column('role_bot', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_history', 'role_bot')
    # ### end Alembic commands ###
